"""use.py — One-import brain wrapper for any day-to-day model use.

  from use import BrainSession

  session = BrainSession()                             # reads ANTHROPIC_API_KEY
  agent   = session.agent("claude-haiku-4-5-20251001") # or any model / callable

  # Your normal loop:
  result = agent("write X")                            # predict → generate → return
  print(f"p_fail={session.p_fail:.0%}")                # how likely was this to fail?

  success = my_tests_pass(result)
  session.teach(success, metadata="specific diagnosis") # one line — brain learns

When p_fail exceeds the threshold the brain automatically injects a specific,
causal explanation into the prompt: not "a similar task failed" but "your **
is LEFT-associative (while loop) — 2**3**2 gives 64 not 512. Fix: right-recurse."

The intervention is generated by an InterventionReasoner that:
  1. Retrieves the nearest stored failure trajectory (by task similarity)
  2. Compares trajectory shape (drift, step-type sequence, self-corrections)
  3. Calls haiku to generate a specific STOP:/FIX: message
  4. Falls back to a structured warning if the LLM call fails

Cost: one embedding call per task. One haiku call when the brain fires.
Works with: any Anthropic model string, any OpenAI model string, any callable.
"""
from __future__ import annotations

import os
import re
from typing import Callable

from trace_use import BrainAgent
from trace_use.agents import build_embedder


# ── Routing ──────────────────────────────────────────────────────────────────

_DEFAULT_SYSTEM = (
    "You are a helpful assistant. "
    "When writing code, output it in a single ```python ... ``` code block. "
    "Embed your reasoning as comments inside the block."
)


def _make_agent(model_or_fn, system: str = _DEFAULT_SYSTEM) -> Callable:
    """Turn a model name or callable into a (prompt) -> (text, tokens) callable."""
    if callable(model_or_fn) and not isinstance(model_or_fn, str):
        fn = model_or_fn
        def _wrap(prompt: str) -> tuple[str, int]:
            r = fn(prompt)
            if isinstance(r, tuple):
                return r[0], r[1] if len(r) > 1 else 0
            return str(r), 0
        return _wrap

    model: str = model_or_fn
    if "claude" in model.lower():
        import anthropic
        client = anthropic.Anthropic()
        needs_thinking = any(m in model for m in ("sonnet-4", "opus-4"))
        def _claude(prompt: str) -> tuple[str, int]:
            kwargs: dict = {}
            if needs_thinking:
                kwargs["thinking"] = {"type": "enabled", "budget_tokens": 5000}
            msg = client.messages.create(
                model=model, max_tokens=4096,
                system=system,
                messages=[{"role": "user", "content": prompt}],
                **kwargs,
            )
            text = "".join(
                b.text if hasattr(b, "text") else getattr(b, "thinking", "")
                for b in msg.content
            )
            return text, msg.usage.input_tokens + msg.usage.output_tokens
        return _claude

    if "gpt" in model.lower() or "o1" in model.lower() or "o3" in model.lower():
        from openai import OpenAI
        client = OpenAI()
        def _openai(prompt: str) -> tuple[str, int]:
            rsp = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
            )
            text   = rsp.choices[0].message.content or ""
            tokens = rsp.usage.total_tokens if rsp.usage else 0
            return text, tokens
        return _openai

    raise ValueError(f"Unknown model: {model!r}. Pass a callable for custom models.")


# ── BrainSession ─────────────────────────────────────────────────────────────

class BrainSession:
    """Brain wrapper for any model. Predicts failures from past traces.

    Maintains a latent trajectory store: each completed task is stored as an
    ordered sequence of LatentSteps (embedding + drift + step_type). Before
    each new generation, the current prompt is compared to stored task prompts
    to detect whether this task resembles past failures. When it does, an
    InterventionReasoner generates a specific, causal explanation that is
    injected into the prompt.

    Usage::

        session = BrainSession()
        agent   = session.agent("claude-haiku-4-5-20251001")

        result  = agent("write a parser for X")
        print(f"p_fail={session.p_fail:.0%}  fired={session.fired}")
        print(f"explanation={session.explanation}")

        success = run_tests(result)
        session.teach(success, metadata="specific diagnosis of what failed")

    Args:
        threshold:   p_fail above this → inject failure context into prompt.
                     Default 0.35. Lower = more aggressive intervention.
        k:           kNN neighbours to consider. Default 5.
        use_llm_intervention: If True (default), call haiku to generate a
                     specific STOP:/FIX: intervention message. If False, use
                     the fast structured warning (no extra LLM call).
    """

    def __init__(
        self,
        threshold: float = 0.35,
        k: int = 5,
        use_llm_intervention: bool = True,
    ):
        self._embedder   = build_embedder()
        self._brain      = BrainAgent(
            self._embedder, k=k, threshold=threshold,
            check_interval=9999, min_chars=999999,   # no mid-gen thread in BrainSession
        )
        self._use_llm    = use_llm_intervention
        self._last_text  = ""
        self._last_prompt = ""

        # Per-call state, set by _monitored()
        self._p_fail:      float | None = None
        self._warning:     str   | None = None
        self._fired:       bool         = False
        self._explanation: str   | None = None

    # ── public ───────────────────────────────────────────────────────────────

    def agent(self, model_or_fn, system: str = _DEFAULT_SYSTEM) -> Callable[[str], str]:
        """Return a drop-in replacement for your model with brain monitoring.

        The returned callable takes a prompt string and returns the response text.

        Pre-generation flow:
          1. Compare prompt to stored task prompts (task-level similarity)
          2. If P(fail) ≥ threshold: call InterventionReasoner for a specific
             STOP:/FIX: message based on the nearest stored failure trajectory
          3. Inject the specific explanation into the prompt
          4. Generate with the enriched prompt

        The injected context is specific enough to actually fix the failure:
        it names the exact bug and the exact fix, not "reconsider approach".
        """
        _inner  = _make_agent(model_or_fn, system=system)
        session = self

        def _monitored(prompt: str) -> str:
            session._last_prompt = prompt
            session._brain._current_task_str = prompt[:300]

            # Pre-generation: compare prompt to stored task prompts
            p_fail, warning = session._brain.predict_pre_generation(
                prompt, use_llm=session._use_llm
            )

            session._p_fail      = p_fail
            session._warning     = warning
            session._fired       = warning is not None
            session._explanation = warning

            # Inject specific intervention context if brain flagged high risk
            if warning:
                augmented = (
                    f"[BRAIN WARNING — P(fail)={p_fail:.0%}]\n"
                    f"{warning}\n\n"
                    f"Original request:\n{prompt}"
                )
            else:
                augmented = prompt

            # Generate
            result = _inner(augmented)
            text   = result[0] if isinstance(result, tuple) else str(result)
            session._last_text = text
            return text

        _monitored.__name__ = (
            f"brain({model_or_fn if isinstance(model_or_fn, str) else getattr(model_or_fn, '__name__', 'fn')})"
        )
        return _monitored

    def teach(self, success: bool | int, metadata: str = "") -> None:
        """Tell the brain whether the last generation succeeded.

        metadata: diagnosis of what went wrong (or right). Shown verbatim in
        future warnings when a similar task is attempted. Be specific — good
        metadata directly improves intervention quality.
        """
        if not self._last_text:
            return
        label = int(bool(success))
        self._brain.store(self._last_text, label, metadata)
        self._last_text   = ""
        self._last_prompt = ""

    def seed(self, items: list[dict]) -> None:
        """Pre-populate with known failure/pass patterns before any live tasks.

        items: list of {'trace': str, 'label': int, 'metadata': str}
        """
        self._brain.seed(items)

    # ── inspection ───────────────────────────────────────────────────────────

    @property
    def p_fail(self) -> float | None:
        """P(fail) computed before the last generation. None = not enough data."""
        return self._p_fail

    @property
    def fired(self) -> bool:
        """True if the brain injected failure context into the last prompt."""
        return self._fired

    @property
    def warning(self) -> str | None:
        """The raw warning text injected (if any)."""
        return self._warning

    @property
    def explanation(self) -> str | None:
        """The specific STOP:/FIX: intervention generated by InterventionReasoner."""
        return self._explanation

    @property
    def n_stored(self) -> int:
        return self._brain.n_stored

    @property
    def n_pass(self) -> int:
        return self._brain.n_pass

    @property
    def n_fail(self) -> int:
        return self._brain.n_fail

    def summary(self) -> None:
        """Print a one-line summary of the session."""
        store = self._brain.failure_store
        _, labels = store.all_vecs()
        n_pass = sum(l == 1 for l in labels)
        n_fail = sum(l == 0 for l in labels)
        print(
            f"BrainSession: {len(labels)} tasks stored  "
            f"{n_pass}✓ {n_fail}✗  "
            f"threshold={self._brain._traj_store._threshold}"
        )

    def store_snapshot(self) -> tuple:
        """Return (embeddings, labels) for plotting or analysis."""
        return self._brain.failure_store.all_vecs()
